# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.CharField(max_length=100),
        ),
    ]
