# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170920_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ip', models.CharField(max_length=100)),
                ('server_name', models.CharField(max_length=100)),
                ('server_password', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=100)),
                ('server_cpu', models.CharField(max_length=100)),
                ('server_harddisk', models.CharField(max_length=100)),
                ('server_Remark', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('consumer_type', models.BooleanField()),
                ('web_version', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('apps', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=100)),
                ('counsumer_Remark', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='consumer_server',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Consumer_version'),
        ),
    ]
