# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20170921_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumer_version',
            new_name='Consumer',
        ),
        migrations.RenameModel(
            old_name='Consumer_server',
            new_name='Server',
        ),
    ]
